baseurl = "http://christianprado.com/blog/"
languageCode = "en-us"
title = "Blog"
theme = "hugo-lithium-theme"
googleAnalytics = ""
disqusShortname = ""
relativeURLs = false

[permalinks]
    post = "/:year/:month/:day/:title/"
    page = "/:title/"

[[menu.main]]
    name = "Christian Prado"
    url = "https://christianprado.com"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/codechristian"

[params]
    description = ""

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"
